/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const AboutSection = IDL.Record({
  'media' : IDL.Opt(ExternalBlob),
  'title' : IDL.Text,
  'content' : IDL.Text,
  'link' : IDL.Bool,
});
export const MembershipRegistration = IDL.Record({
  'additionalInfo' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'address' : IDL.Text,
  'phone' : IDL.Text,
});
export const Branding = IDL.Record({
  'logo' : IDL.Opt(ExternalBlob),
  'name' : IDL.Text,
  'otherMedia' : IDL.Opt(ExternalBlob),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });
export const Club = IDL.Record({
  'id' : IDL.Nat,
  'motto' : IDL.Text,
  'aims' : IDL.Text,
  'name' : IDL.Text,
  'activities' : IDL.Text,
  'history' : IDL.Text,
  'slogan' : IDL.Text,
  'achievements' : IDL.Text,
  'profilePicture' : IDL.Opt(IDL.Text),
  'program' : IDL.Text,
});
export const HomePageSection = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'image' : IDL.Opt(ExternalBlob),
});
export const SocialMediaLinks = IDL.Record({
  'linkedin' : IDL.Text,
  'tiktok' : IDL.Text,
  'twitter' : IDL.Text,
  'instagram' : IDL.Text,
  'whatsapp' : IDL.Text,
  'facebook' : IDL.Text,
  'youtube' : IDL.Text,
});

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createClub' : IDL.Func(
      [
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'deleteClub' : IDL.Func([IDL.Nat], [], []),
  'getAboutSections' : IDL.Func([], [IDL.Vec(AboutSection)], ['query']),
  'getAllMembershipRegistrations' : IDL.Func(
      [],
      [IDL.Vec(MembershipRegistration)],
      ['query'],
    ),
  'getBrandingMedia' : IDL.Func([], [IDL.Opt(Branding)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
  'getHistoryContent' : IDL.Func(
      [],
      [IDL.Record({ 'media' : IDL.Opt(ExternalBlob), 'content' : IDL.Text })],
      ['query'],
    ),
  'getHomePageSections' : IDL.Func([], [IDL.Vec(HomePageSection)], ['query']),
  'getSocialMediaLinks' : IDL.Func([], [IDL.Opt(SocialMediaLinks)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'setSocialMediaLinks' : IDL.Func([SocialMediaLinks], [], []),
  'submitMembershipRegistration' : IDL.Func([MembershipRegistration], [], []),
  'updateAboutSections' : IDL.Func([IDL.Vec(AboutSection)], [], []),
  'updateBrandingMedia' : IDL.Func([Branding], [], []),
  'updateClub' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Opt(IDL.Text),
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateHistoryContent' : IDL.Func([IDL.Text, IDL.Opt(ExternalBlob)], [], []),
  'updateHomePageSections' : IDL.Func([IDL.Vec(HomePageSection)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const AboutSection = IDL.Record({
    'media' : IDL.Opt(ExternalBlob),
    'title' : IDL.Text,
    'content' : IDL.Text,
    'link' : IDL.Bool,
  });
  const MembershipRegistration = IDL.Record({
    'additionalInfo' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'address' : IDL.Text,
    'phone' : IDL.Text,
  });
  const Branding = IDL.Record({
    'logo' : IDL.Opt(ExternalBlob),
    'name' : IDL.Text,
    'otherMedia' : IDL.Opt(ExternalBlob),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  const Club = IDL.Record({
    'id' : IDL.Nat,
    'motto' : IDL.Text,
    'aims' : IDL.Text,
    'name' : IDL.Text,
    'activities' : IDL.Text,
    'history' : IDL.Text,
    'slogan' : IDL.Text,
    'achievements' : IDL.Text,
    'profilePicture' : IDL.Opt(IDL.Text),
    'program' : IDL.Text,
  });
  const HomePageSection = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'image' : IDL.Opt(ExternalBlob),
  });
  const SocialMediaLinks = IDL.Record({
    'linkedin' : IDL.Text,
    'tiktok' : IDL.Text,
    'twitter' : IDL.Text,
    'instagram' : IDL.Text,
    'whatsapp' : IDL.Text,
    'facebook' : IDL.Text,
    'youtube' : IDL.Text,
  });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createClub' : IDL.Func(
        [
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'deleteClub' : IDL.Func([IDL.Nat], [], []),
    'getAboutSections' : IDL.Func([], [IDL.Vec(AboutSection)], ['query']),
    'getAllMembershipRegistrations' : IDL.Func(
        [],
        [IDL.Vec(MembershipRegistration)],
        ['query'],
      ),
    'getBrandingMedia' : IDL.Func([], [IDL.Opt(Branding)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getClubs' : IDL.Func([], [IDL.Vec(Club)], ['query']),
    'getHistoryContent' : IDL.Func(
        [],
        [IDL.Record({ 'media' : IDL.Opt(ExternalBlob), 'content' : IDL.Text })],
        ['query'],
      ),
    'getHomePageSections' : IDL.Func([], [IDL.Vec(HomePageSection)], ['query']),
    'getSocialMediaLinks' : IDL.Func(
        [],
        [IDL.Opt(SocialMediaLinks)],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'setSocialMediaLinks' : IDL.Func([SocialMediaLinks], [], []),
    'submitMembershipRegistration' : IDL.Func([MembershipRegistration], [], []),
    'updateAboutSections' : IDL.Func([IDL.Vec(AboutSection)], [], []),
    'updateBrandingMedia' : IDL.Func([Branding], [], []),
    'updateClub' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Opt(IDL.Text),
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateHistoryContent' : IDL.Func(
        [IDL.Text, IDL.Opt(ExternalBlob)],
        [],
        [],
      ),
    'updateHomePageSections' : IDL.Func([IDL.Vec(HomePageSection)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };