/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AboutSection {
  'media' : [] | [ExternalBlob],
  'title' : string,
  'content' : string,
  'link' : boolean,
}
export interface Branding {
  'logo' : [] | [ExternalBlob],
  'name' : string,
  'otherMedia' : [] | [ExternalBlob],
}
export interface Club {
  'id' : bigint,
  'motto' : string,
  'aims' : string,
  'name' : string,
  'activities' : string,
  'history' : string,
  'slogan' : string,
  'achievements' : string,
  'profilePicture' : [] | [string],
  'program' : string,
}
export interface Event {
  'id' : bigint,
  'media' : [] | [ExternalBlob],
  'organizer' : string,
  'title' : string,
  'description' : string,
  'dateTime' : string,
  'location' : string,
}
export type ExternalBlob = Uint8Array;
export interface HomePageSection {
  'title' : string,
  'description' : string,
  'image' : [] | [ExternalBlob],
}
export interface MembershipRegistration {
  'additionalInfo' : string,
  'name' : string,
  'email' : string,
  'address' : string,
  'phone' : string,
}
export interface SocialMediaLinks {
  'linkedin' : string,
  'tiktok' : string,
  'twitter' : string,
  'instagram' : string,
  'whatsapp' : string,
  'facebook' : string,
  'youtube' : string,
}
export interface UserProfile { 'name' : string }
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _CaffeineStorageCreateCertificateResult {
  'method' : string,
  'blob_hash' : string,
}
export interface _CaffeineStorageRefillInformation {
  'proposed_top_up_amount' : [] | [bigint],
}
export interface _CaffeineStorageRefillResult {
  'success' : [] | [boolean],
  'topped_up_amount' : [] | [bigint],
}
export interface _SERVICE {
  '_caffeineStorageBlobIsLive' : ActorMethod<[Uint8Array], boolean>,
  '_caffeineStorageBlobsToDelete' : ActorMethod<[], Array<Uint8Array>>,
  '_caffeineStorageConfirmBlobDeletion' : ActorMethod<
    [Array<Uint8Array>],
    undefined
  >,
  '_caffeineStorageCreateCertificate' : ActorMethod<
    [string],
    _CaffeineStorageCreateCertificateResult
  >,
  '_caffeineStorageRefillCashier' : ActorMethod<
    [[] | [_CaffeineStorageRefillInformation]],
    _CaffeineStorageRefillResult
  >,
  '_caffeineStorageUpdateGatewayPrincipals' : ActorMethod<[], undefined>,
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createClub' : ActorMethod<
    [
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    bigint
  >,
  'createOrUpdateEvent' : ActorMethod<[Event], undefined>,
  'deleteClub' : ActorMethod<[bigint], undefined>,
  'deleteEvent' : ActorMethod<[bigint], undefined>,
  'getAboutSections' : ActorMethod<[], Array<AboutSection>>,
  'getAllMembershipRegistrations' : ActorMethod<
    [],
    Array<MembershipRegistration>
  >,
  'getAndroidApkUrl' : ActorMethod<[], string>,
  'getBrandingMedia' : ActorMethod<[], [] | [Branding]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getClubs' : ActorMethod<[], Array<Club>>,
  'getEvent' : ActorMethod<[bigint], [] | [Event]>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getHistoryContent' : ActorMethod<
    [],
    { 'media' : [] | [ExternalBlob], 'content' : string }
  >,
  'getHomePageSections' : ActorMethod<[], Array<HomePageSection>>,
  'getSocialMediaLinks' : ActorMethod<[], [] | [SocialMediaLinks]>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setAndroidApkUrl' : ActorMethod<[string], undefined>,
  'setSocialMediaLinks' : ActorMethod<[SocialMediaLinks], undefined>,
  'submitMembershipRegistration' : ActorMethod<
    [MembershipRegistration],
    undefined
  >,
  'updateAboutSections' : ActorMethod<[Array<AboutSection>], undefined>,
  'updateBrandingMedia' : ActorMethod<[Branding], undefined>,
  'updateClub' : ActorMethod<
    [
      bigint,
      string,
      [] | [string],
      string,
      string,
      string,
      string,
      string,
      string,
      string,
    ],
    undefined
  >,
  'updateHistoryContent' : ActorMethod<
    [string, [] | [ExternalBlob]],
    undefined
  >,
  'updateHomePageSections' : ActorMethod<[Array<HomePageSection>], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];