/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface HomePageSection {
    title: string;
    description: string;
    image?: ExternalBlob;
}
export interface AboutSection {
    media?: ExternalBlob;
    title: string;
    content: string;
    link: boolean;
}
export interface SocialMediaLinks {
    linkedin: string;
    tiktok: string;
    twitter: string;
    instagram: string;
    whatsapp: string;
    facebook: string;
    youtube: string;
}
export interface MembershipRegistration {
    additionalInfo: string;
    name: string;
    email: string;
    address: string;
    phone: string;
}
export interface _CaffeineStorageRefillInformation {
    proposed_top_up_amount?: bigint;
}
export interface _CaffeineStorageCreateCertificateResult {
    method: string;
    blob_hash: string;
}
export interface Club {
    id: bigint;
    motto: string;
    aims: string;
    name: string;
    activities: string;
    history: string;
    slogan: string;
    achievements: string;
    profilePicture?: string;
    program: string;
}
export interface Branding {
    logo?: ExternalBlob;
    name: string;
    otherMedia?: ExternalBlob;
}
export interface UserProfile {
    name: string;
}
export interface _CaffeineStorageRefillResult {
    success?: boolean;
    topped_up_amount?: bigint;
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _caffeineStorageBlobIsLive(hash: Uint8Array): Promise<boolean>;
    _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>>;
    _caffeineStorageConfirmBlobDeletion(blobs: Array<Uint8Array>): Promise<void>;
    _caffeineStorageCreateCertificate(blobHash: string): Promise<_CaffeineStorageCreateCertificateResult>;
    _caffeineStorageRefillCashier(refillInformation: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult>;
    _caffeineStorageUpdateGatewayPrincipals(): Promise<void>;
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createClub(name: string, profilePicture: string | null, aims: string, motto: string, slogan: string, achievements: string, program: string, activities: string, history: string): Promise<bigint>;
    deleteClub(id: bigint): Promise<void>;
    getAboutSections(): Promise<Array<AboutSection>>;
    getAllMembershipRegistrations(): Promise<Array<MembershipRegistration>>;
    getBrandingMedia(): Promise<Branding | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getClubs(): Promise<Array<Club>>;
    getHistoryContent(): Promise<{
        media?: ExternalBlob;
        content: string;
    }>;
    getHomePageSections(): Promise<Array<HomePageSection>>;
    getSocialMediaLinks(): Promise<SocialMediaLinks | null>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(_profile: UserProfile): Promise<void>;
    setSocialMediaLinks(links: SocialMediaLinks): Promise<void>;
    submitMembershipRegistration(registration: MembershipRegistration): Promise<void>;
    updateAboutSections(sections: Array<AboutSection>): Promise<void>;
    updateBrandingMedia(branding: Branding): Promise<void>;
    updateClub(id: bigint, name: string, profilePicture: string | null, aims: string, motto: string, slogan: string, achievements: string, program: string, activities: string, history: string): Promise<void>;
    updateHistoryContent(content: string, media: ExternalBlob | null): Promise<void>;
    updateHomePageSections(sections: Array<HomePageSection>): Promise<void>;
}
import type { AboutSection as _AboutSection, Branding as _Branding, Club as _Club, ExternalBlob as _ExternalBlob, HomePageSection as _HomePageSection, SocialMediaLinks as _SocialMediaLinks, UserProfile as _UserProfile, UserRole as _UserRole, _CaffeineStorageRefillInformation as __CaffeineStorageRefillInformation, _CaffeineStorageRefillResult as __CaffeineStorageRefillResult } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _caffeineStorageBlobIsLive(arg0: Uint8Array): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobIsLive(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobIsLive(arg0);
            return result;
        }
    }
    async _caffeineStorageBlobsToDelete(): Promise<Array<Uint8Array>> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageBlobsToDelete();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageBlobsToDelete();
            return result;
        }
    }
    async _caffeineStorageConfirmBlobDeletion(arg0: Array<Uint8Array>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageConfirmBlobDeletion(arg0);
            return result;
        }
    }
    async _caffeineStorageCreateCertificate(arg0: string): Promise<_CaffeineStorageCreateCertificateResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageCreateCertificate(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageCreateCertificate(arg0);
            return result;
        }
    }
    async _caffeineStorageRefillCashier(arg0: _CaffeineStorageRefillInformation | null): Promise<_CaffeineStorageRefillResult> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageRefillCashier(to_candid_opt_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid__CaffeineStorageRefillResult_n4(this._uploadFile, this._downloadFile, result);
        }
    }
    async _caffeineStorageUpdateGatewayPrincipals(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._caffeineStorageUpdateGatewayPrincipals();
            return result;
        }
    }
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n8(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createClub(arg0: string, arg1: string | null, arg2: string, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createClub(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createClub(arg0, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg1), arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async deleteClub(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteClub(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteClub(arg0);
            return result;
        }
    }
    async getAboutSections(): Promise<Array<AboutSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAboutSections();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAboutSections();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllMembershipRegistrations(): Promise<Array<MembershipRegistration>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMembershipRegistrations();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMembershipRegistrations();
            return result;
        }
    }
    async getBrandingMedia(): Promise<Branding | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBrandingMedia();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBrandingMedia();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getClubs(): Promise<Array<Club>> {
        if (this.processError) {
            try {
                const result = await this.actor.getClubs();
                return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getClubs();
            return from_candid_vec_n22(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHistoryContent(): Promise<{
        media?: ExternalBlob;
        content: string;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getHistoryContent();
                return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHistoryContent();
            return from_candid_record_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getHomePageSections(): Promise<Array<HomePageSection>> {
        if (this.processError) {
            try {
                const result = await this.actor.getHomePageSections();
                return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getHomePageSections();
            return from_candid_vec_n27(this._uploadFile, this._downloadFile, result);
        }
    }
    async getSocialMediaLinks(): Promise<SocialMediaLinks | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getSocialMediaLinks();
                return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getSocialMediaLinks();
            return from_candid_opt_n30(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n19(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async setSocialMediaLinks(arg0: SocialMediaLinks): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setSocialMediaLinks(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setSocialMediaLinks(arg0);
            return result;
        }
    }
    async submitMembershipRegistration(arg0: MembershipRegistration): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.submitMembershipRegistration(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitMembershipRegistration(arg0);
            return result;
        }
    }
    async updateAboutSections(arg0: Array<AboutSection>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateAboutSections(await to_candid_vec_n31(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateAboutSections(await to_candid_vec_n31(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateBrandingMedia(arg0: Branding): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateBrandingMedia(await to_candid_Branding_n35(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateBrandingMedia(await to_candid_Branding_n35(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async updateClub(arg0: bigint, arg1: string, arg2: string | null, arg3: string, arg4: string, arg5: string, arg6: string, arg7: string, arg8: string, arg9: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateClub(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateClub(arg0, arg1, to_candid_opt_n10(this._uploadFile, this._downloadFile, arg2), arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateHistoryContent(arg0: string, arg1: ExternalBlob | null): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHistoryContent(arg0, await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHistoryContent(arg0, await to_candid_opt_n37(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateHomePageSections(arg0: Array<HomePageSection>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateHomePageSections(await to_candid_vec_n38(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateHomePageSections(await to_candid_vec_n38(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
}
async function from_candid_AboutSection_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _AboutSection): Promise<AboutSection> {
    return await from_candid_record_n13(_uploadFile, _downloadFile, value);
}
async function from_candid_Branding_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Branding): Promise<Branding> {
    return await from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_Club_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Club): Club {
    return from_candid_record_n24(_uploadFile, _downloadFile, value);
}
async function from_candid_ExternalBlob_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ExternalBlob): Promise<ExternalBlob> {
    return await _downloadFile(value);
}
async function from_candid_HomePageSection_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _HomePageSection): Promise<HomePageSection> {
    return await from_candid_record_n29(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function from_candid__CaffeineStorageRefillResult_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: __CaffeineStorageRefillResult): _CaffeineStorageRefillResult {
    return from_candid_record_n5(_uploadFile, _downloadFile, value);
}
async function from_candid_opt_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ExternalBlob]): Promise<ExternalBlob | null> {
    return value.length === 0 ? null : await from_candid_ExternalBlob_n15(_uploadFile, _downloadFile, value[0]);
}
async function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Branding]): Promise<Branding | null> {
    return value.length === 0 ? null : await from_candid_Branding_n17(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_SocialMediaLinks]): SocialMediaLinks | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [boolean]): boolean | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
async function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media: [] | [_ExternalBlob];
    title: string;
    content: string;
    link: boolean;
}): Promise<{
    media?: ExternalBlob;
    title: string;
    content: string;
    link: boolean;
}> {
    return {
        media: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.media)),
        title: value.title,
        content: value.content,
        link: value.link
    };
}
async function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo: [] | [_ExternalBlob];
    name: string;
    otherMedia: [] | [_ExternalBlob];
}): Promise<{
    logo?: ExternalBlob;
    name: string;
    otherMedia?: ExternalBlob;
}> {
    return {
        logo: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.logo)),
        name: value.name,
        otherMedia: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.otherMedia))
    };
}
function from_candid_record_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    motto: string;
    aims: string;
    name: string;
    activities: string;
    history: string;
    slogan: string;
    achievements: string;
    profilePicture: [] | [string];
    program: string;
}): {
    id: bigint;
    motto: string;
    aims: string;
    name: string;
    activities: string;
    history: string;
    slogan: string;
    achievements: string;
    profilePicture?: string;
    program: string;
} {
    return {
        id: value.id,
        motto: value.motto,
        aims: value.aims,
        name: value.name,
        activities: value.activities,
        history: value.history,
        slogan: value.slogan,
        achievements: value.achievements,
        profilePicture: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.profilePicture)),
        program: value.program
    };
}
async function from_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media: [] | [_ExternalBlob];
    content: string;
}): Promise<{
    media?: ExternalBlob;
    content: string;
}> {
    return {
        media: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.media)),
        content: value.content
    };
}
async function from_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
}): Promise<{
    title: string;
    description: string;
    image?: ExternalBlob;
}> {
    return {
        title: value.title,
        description: value.description,
        image: record_opt_to_undefined(await from_candid_opt_n14(_uploadFile, _downloadFile, value.image))
    };
}
function from_candid_record_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    success: [] | [boolean];
    topped_up_amount: [] | [bigint];
}): {
    success?: boolean;
    topped_up_amount?: bigint;
} {
    return {
        success: record_opt_to_undefined(from_candid_opt_n6(_uploadFile, _downloadFile, value.success)),
        topped_up_amount: record_opt_to_undefined(from_candid_opt_n7(_uploadFile, _downloadFile, value.topped_up_amount))
    };
}
function from_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
async function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_AboutSection>): Promise<Array<AboutSection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_AboutSection_n12(_uploadFile, _downloadFile, x)));
}
function from_candid_vec_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Club>): Array<Club> {
    return value.map((x)=>from_candid_Club_n23(_uploadFile, _downloadFile, x));
}
async function from_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_HomePageSection>): Promise<Array<HomePageSection>> {
    return await Promise.all(value.map(async (x)=>await from_candid_HomePageSection_n28(_uploadFile, _downloadFile, x)));
}
async function to_candid_AboutSection_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: AboutSection): Promise<_AboutSection> {
    return await to_candid_record_n33(_uploadFile, _downloadFile, value);
}
async function to_candid_Branding_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Branding): Promise<_Branding> {
    return await to_candid_record_n36(_uploadFile, _downloadFile, value);
}
async function to_candid_ExternalBlob_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob): Promise<_ExternalBlob> {
    return await _uploadFile(value);
}
async function to_candid_HomePageSection_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: HomePageSection): Promise<_HomePageSection> {
    return await to_candid_record_n40(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function to_candid__CaffeineStorageRefillInformation_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation): __CaffeineStorageRefillInformation {
    return to_candid_record_n3(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CaffeineStorageRefillInformation | null): [] | [__CaffeineStorageRefillInformation] {
    return value === null ? candid_none() : candid_some(to_candid__CaffeineStorageRefillInformation_n2(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
async function to_candid_opt_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ExternalBlob | null): Promise<[] | [_ExternalBlob]> {
    return value === null ? candid_none() : candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value));
}
function to_candid_record_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    proposed_top_up_amount?: bigint;
}): {
    proposed_top_up_amount: [] | [bigint];
} {
    return {
        proposed_top_up_amount: value.proposed_top_up_amount ? candid_some(value.proposed_top_up_amount) : candid_none()
    };
}
async function to_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    media?: ExternalBlob;
    title: string;
    content: string;
    link: boolean;
}): Promise<{
    media: [] | [_ExternalBlob];
    title: string;
    content: string;
    link: boolean;
}> {
    return {
        media: value.media ? candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.media)) : candid_none(),
        title: value.title,
        content: value.content,
        link: value.link
    };
}
async function to_candid_record_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    logo?: ExternalBlob;
    name: string;
    otherMedia?: ExternalBlob;
}): Promise<{
    logo: [] | [_ExternalBlob];
    name: string;
    otherMedia: [] | [_ExternalBlob];
}> {
    return {
        logo: value.logo ? candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.logo)) : candid_none(),
        name: value.name,
        otherMedia: value.otherMedia ? candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.otherMedia)) : candid_none()
    };
}
async function to_candid_record_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    image?: ExternalBlob;
}): Promise<{
    title: string;
    description: string;
    image: [] | [_ExternalBlob];
}> {
    return {
        title: value.title,
        description: value.description,
        image: value.image ? candid_some(await to_candid_ExternalBlob_n34(_uploadFile, _downloadFile, value.image)) : candid_none()
    };
}
function to_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
async function to_candid_vec_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<AboutSection>): Promise<Array<_AboutSection>> {
    return await Promise.all(value.map(async (x)=>await to_candid_AboutSection_n32(_uploadFile, _downloadFile, x)));
}
async function to_candid_vec_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<HomePageSection>): Promise<Array<_HomePageSection>> {
    return await Promise.all(value.map(async (x)=>await to_candid_HomePageSection_n39(_uploadFile, _downloadFile, x)));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
